export const apiPaths = {
  clientBaseUrl: process.env.NEXT_PUBLIC_CLIENT_BASE_URL,
  serverUrl: process.env.NEXT_PUBLIC_SERVER_URL,
  baseUrl: `${process.env.NEXT_PUBLIC_SERVER_URL}` + '/api/v1/',
  registerUrl: 'user/register/',
  loginUrl: 'user/login/',
  profileUrl: 'user/profile/',
  publicProfileUrl: 'user/public/profile',
  changeCurrentPasswordUrl: 'user/change-password/',
  resetPasswordUrl: 'user/reset-password/',
  sendForgotPasswordEmailUrl: 'user/send-forgot-password-email/',
  getCardTemplatesUrl: 'templates/',
  getCardUrl: 'cards/',
  getDefaultCardUrl: 'default/card/',
  updateContentUrl: 'card/update-content/',
  cardsUrl: 'cards/',
  connectUrl: 'connect/',
  connectionRequestUrl: 'connect/requests/',
  getTeamsCategoryUrl: 'team-categories',
  teamsUrl: 'teams/',
  teamUrl: 'team/',
  teamTemplatesUrl: 'team/template/',
  teamMembersUrl: 'team/members/',
  teamRequestUrl: 'team/requests/',
  requestByTeamUrl: 'team/requests-by-team/',
  getSocialInfosUrl: 'card-infos',
  getPublicCardsUrl: 'public/cards/',
  favoritesUrl: 'favorites/'
};
