'use client';

import { Metadata } from 'next';
import { useRouter } from 'next/navigation';
import { useSession } from 'next-auth/react';
import { useEffect } from 'react';
import { toast } from 'react-toastify';

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
};

const LoginLayout = ({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) => {
  const router = useRouter();
  const { data: session, status } = useSession();

  // useEffect(() => {
  //   // if (status === 'authenticated') {
  //   //   router.push('./dashboard');
  //   //   return;
  //   // }
  //   //Runs only on the first render
  // }, [status, session]);

  useEffect(() => {
    if (status === 'authenticated') {
      toast.success('User already logged in');
      router.push('./dashboard');
      return;
    }
  }, [status]);

  if (status === 'loading') {
    return <p>loading...</p>;
  }

  if (status === 'unauthenticated') {
    return (
      <section>
        <nav></nav>
        {children}
      </section>
    );
  }
};

export default LoginLayout;
