import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from '../core/redux/providers';
import './globals.css';
import { ConvexClientProvider } from './providers/ConvexClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cardaxe',
  description: 'Generated by create next app',
  other: {
    "google-site-verification": "g7cfd-RHg_NRmNCiak9ccc8N_er7KEgyXjC9B0h4TDY",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={cn(inter.className)}>
        <Toaster />
        <div id="popUpModal" />
        <Providers>
          <ConvexClientProvider>
            <>{children}</>
          </ConvexClientProvider>
        </Providers>
        {/* <Notification /> */}
      </body>
    </html>
  );
}
